TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#==================================================
# Build an IOC support library

LIBRARY_IOC += tds3000

DBD += tdsSup.dbd
DBD += sncTds3x.dbd

# The following are compiled and added to the Support library
tds3000_SRCS += genSub.c tdsGSub.c
tds3000_SRCS += sncTds3x.st

tds3000_LIBS += $(EPICS_BASE_IOC_LIBS)

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

